name: Charles Cantin - Photographe
author: Charles Cantin
url: https://cantin-charles-photographe.netlify.app/
keywords: photographe, professionnel, prestation, sur mesure, photos,
  mariage,   baptême, séminaire, portraits, souvenirs
description: "Charles Cantin, votre photographe professionnel pour tout   type
  de prestation : Sur mesure, mariage, baptême, portrait,..."
